/********************************
*Author: Mohanad Fawzy Sallam   *
*Version: v02                   *
*Date: 19/01/2020               *
*********************************/
#define Conc(b7,b6,b5,b4,b3,b2,b1,b0)				Conc_Helper(b7,b6,b5,b4,b3,b2,b1,b0)
#define Conc_Helper(b7,b6,b5,b4,b3,b2,b1,b0)		0b##b7##b6##b5##b4##b3##b2##b1##b0

#define PORTA_DIR Conc(PORT_U8_PORTA_PIN7_DIR,PORT_U8_PORTA_PIN6_DIR,PORT_U8_PORTA_PIN5_DIR,PORT_U8_PORTA_PIN4_DIR,PORT_U8_PORTA_PIN3_DIR,PORT_U8_PORTA_PIN2_DIR,PORT_U8_PORTA_PIN1_DIR,PORT_U8_PORTA_PIN0_DIR)
#define PORTB_DIR Conc(PORT_U8_PORTB_PIN7_DIR,PORT_U8_PORTB_PIN6_DIR,PORT_U8_PORTB_PIN5_DIR,PORT_U8_PORTB_PIN4_DIR,PORT_U8_PORTB_PIN3_DIR,PORT_U8_PORTB_PIN2_DIR,PORT_U8_PORTB_PIN1_DIR,PORT_U8_PORTB_PIN0_DIR)
#define PORTC_DIR Conc(PORT_U8_PORTC_PIN7_DIR,PORT_U8_PORTC_PIN6_DIR,PORT_U8_PORTC_PIN5_DIR,PORT_U8_PORTC_PIN4_DIR,PORT_U8_PORTC_PIN3_DIR,PORT_U8_PORTC_PIN2_DIR,PORT_U8_PORTC_PIN1_DIR,PORT_U8_PORTC_PIN0_DIR)
#define PORTD_DIR Conc(PORT_U8_PORTD_PIN7_DIR,PORT_U8_PORTD_PIN6_DIR,PORT_U8_PORTD_PIN5_DIR,PORT_U8_PORTD_PIN4_DIR,PORT_U8_PORTD_PIN3_DIR,PORT_U8_PORTD_PIN2_DIR,PORT_U8_PORTD_PIN1_DIR,PORT_U8_PORTD_PIN0_DIR)

#define PORTA_INITIAL_VALUE  Conc(PORT_U8_PORTA_PIN7_INITIAL_VALUE,PORT_U8_PORTA_PIN6_INITIAL_VALUE,PORT_U8_PORTA_PIN5_INITIAL_VALUE,PORT_U8_PORTA_PIN4_INITIAL_VALUE,PORT_U8_PORTA_PIN3_INITIAL_VALUE,PORT_U8_PORTA_PIN2_INITIAL_VALUE,PORT_U8_PORTA_PIN1_INITIAL_VALUE,PORT_U8_PORTA_PIN0_INITIAL_VALUE)
#define PORTB_INITIAL_VALUE  Conc(PORT_U8_PORTB_PIN7_INITIAL_VALUE,PORT_U8_PORTB_PIN6_INITIAL_VALUE,PORT_U8_PORTB_PIN5_INITIAL_VALUE,PORT_U8_PORTB_PIN4_INITIAL_VALUE,PORT_U8_PORTB_PIN3_INITIAL_VALUE,PORT_U8_PORTB_PIN2_INITIAL_VALUE,PORT_U8_PORTB_PIN1_INITIAL_VALUE,PORT_U8_PORTB_PIN0_INITIAL_VALUE)
#define PORTC_INITIAL_VALUE  Conc(PORT_U8_PORTC_PIN7_INITIAL_VALUE,PORT_U8_PORTC_PIN6_INITIAL_VALUE,PORT_U8_PORTC_PIN5_INITIAL_VALUE,PORT_U8_PORTC_PIN4_INITIAL_VALUE,PORT_U8_PORTC_PIN3_INITIAL_VALUE,PORT_U8_PORTC_PIN2_INITIAL_VALUE,PORT_U8_PORTC_PIN1_INITIAL_VALUE,PORT_U8_PORTC_PIN0_INITIAL_VALUE)
#define PORTD_INITIAL_VALUE  Conc(PORT_U8_PORTD_PIN7_INITIAL_VALUE,PORT_U8_PORTD_PIN6_INITIAL_VALUE,PORT_U8_PORTD_PIN5_INITIAL_VALUE,PORT_U8_PORTD_PIN4_INITIAL_VALUE,PORT_U8_PORTD_PIN3_INITIAL_VALUE,PORT_U8_PORTD_PIN2_INITIAL_VALUE,PORT_U8_PORTD_PIN1_INITIAL_VALUE,PORT_U8_PORTD_PIN0_INITIAL_VALUE)



