/********************************
*Author: Mohanad Fawzy Sallam   *
*Version: v02                   *
*Date: 19/01/2020               *
*********************************/
#define INPUT 0
#define OUTPUT 1
/* input=0, output=1*/ 
#define PORT_U8_PORTA_PIN0_DIR	OUTPUT
#define PORT_U8_PORTA_PIN1_DIR	OUTPUT
#define PORT_U8_PORTA_PIN2_DIR	OUTPUT
#define PORT_U8_PORTA_PIN3_DIR	OUTPUT
#define PORT_U8_PORTA_PIN4_DIR	OUTPUT
#define PORT_U8_PORTA_PIN5_DIR	OUTPUT
#define PORT_U8_PORTA_PIN6_DIR	OUTPUT
#define PORT_U8_PORTA_PIN7_DIR	OUTPUT
#define PORT_U8_PORTB_PIN0_DIR	OUTPUT
#define PORT_U8_PORTB_PIN1_DIR	OUTPUT
#define PORT_U8_PORTB_PIN2_DIR	OUTPUT
#define PORT_U8_PORTB_PIN3_DIR	OUTPUT
#define PORT_U8_PORTB_PIN4_DIR	OUTPUT
#define PORT_U8_PORTB_PIN5_DIR	OUTPUT
#define PORT_U8_PORTB_PIN6_DIR	OUTPUT
#define PORT_U8_PORTB_PIN7_DIR	OUTPUT
#define PORT_U8_PORTC_PIN0_DIR	OUTPUT
#define PORT_U8_PORTC_PIN1_DIR	OUTPUT
#define PORT_U8_PORTC_PIN2_DIR	OUTPUT
#define PORT_U8_PORTC_PIN3_DIR	OUTPUT
#define PORT_U8_PORTC_PIN4_DIR	INPUT
#define PORT_U8_PORTC_PIN5_DIR	INPUT
#define PORT_U8_PORTC_PIN6_DIR	INPUT
#define PORT_U8_PORTC_PIN7_DIR	INPUT
#define PORT_U8_PORTD_PIN0_DIR	INPUT
#define PORT_U8_PORTD_PIN1_DIR	OUTPUT
#define PORT_U8_PORTD_PIN2_DIR	OUTPUT
#define PORT_U8_PORTD_PIN3_DIR	OUTPUT
#define PORT_U8_PORTD_PIN4_DIR	OUTPUT
#define PORT_U8_PORTD_PIN5_DIR	OUTPUT
#define PORT_U8_PORTD_PIN6_DIR	OUTPUT
#define PORT_U8_PORTD_PIN7_DIR	OUTPUT
/**************************************************/
#define LOW 0
#define HIGH 1
/*choose initial value for pins
 * 0:Low for output,floating for input
 * 1:high for output, internal pull up for input*/
#define PORT_U8_PORTA_PIN0_INITIAL_VALUE	LOW
#define PORT_U8_PORTA_PIN1_INITIAL_VALUE	LOW
#define PORT_U8_PORTA_PIN2_INITIAL_VALUE	LOW
#define PORT_U8_PORTA_PIN3_INITIAL_VALUE	LOW
#define PORT_U8_PORTA_PIN4_INITIAL_VALUE	LOW
#define PORT_U8_PORTA_PIN5_INITIAL_VALUE	LOW
#define PORT_U8_PORTA_PIN6_INITIAL_VALUE	LOW
#define PORT_U8_PORTA_PIN7_INITIAL_VALUE	LOW
#define PORT_U8_PORTB_PIN0_INITIAL_VALUE	LOW
#define PORT_U8_PORTB_PIN1_INITIAL_VALUE	LOW
#define PORT_U8_PORTB_PIN2_INITIAL_VALUE	LOW
#define PORT_U8_PORTB_PIN3_INITIAL_VALUE	LOW
#define PORT_U8_PORTB_PIN4_INITIAL_VALUE	HIGH
#define PORT_U8_PORTB_PIN5_INITIAL_VALUE	HIGH
#define PORT_U8_PORTB_PIN6_INITIAL_VALUE	HIGH
#define PORT_U8_PORTB_PIN7_INITIAL_VALUE	HIGH
#define PORT_U8_PORTC_PIN0_INITIAL_VALUE	HIGH
#define PORT_U8_PORTC_PIN1_INITIAL_VALUE	HIGH
#define PORT_U8_PORTC_PIN2_INITIAL_VALUE	HIGH
#define PORT_U8_PORTC_PIN3_INITIAL_VALUE	HIGH
#define PORT_U8_PORTC_PIN4_INITIAL_VALUE	HIGH
#define PORT_U8_PORTC_PIN5_INITIAL_VALUE	HIGH
#define PORT_U8_PORTC_PIN6_INITIAL_VALUE	HIGH
#define PORT_U8_PORTC_PIN7_INITIAL_VALUE	HIGH
#define PORT_U8_PORTD_PIN0_INITIAL_VALUE	LOW
#define PORT_U8_PORTD_PIN1_INITIAL_VALUE	LOW
#define PORT_U8_PORTD_PIN2_INITIAL_VALUE	LOW
#define PORT_U8_PORTD_PIN3_INITIAL_VALUE	LOW
#define PORT_U8_PORTD_PIN4_INITIAL_VALUE	LOW
#define PORT_U8_PORTD_PIN5_INITIAL_VALUE	LOW
#define PORT_U8_PORTD_PIN6_INITIAL_VALUE	LOW
#define PORT_U8_PORTD_PIN7_INITIAL_VALUE	LOW
